-- Built-in exercise library seed — applied via MCP during Plan 02 execution.
-- Re-run with: supabase sql --file supabase/seed.sql
-- All exercises: is_custom = false, created_by = null (visible to all users per RLS policy)
INSERT INTO public.exercises (name, muscle_group, equipment, type, is_custom) VALUES
('Bench Press', 'chest', 'barbell', 'strength', false),
('Incline Dumbbell Press', 'chest', 'dumbbell', 'strength', false),
('Cable Fly', 'chest', 'cable', 'strength', false),
('Push-up', 'chest', 'bodyweight', 'bodyweight', false),
('Dip', 'chest', 'bodyweight', 'bodyweight', false),
('Decline Bench Press', 'chest', 'barbell', 'strength', false),
('Pull-up', 'back', 'bodyweight', 'bodyweight', false),
('Bent-over Row', 'back', 'barbell', 'strength', false),
('Lat Pulldown', 'back', 'cable', 'strength', false),
('Cable Row', 'back', 'cable', 'strength', false),
('Dumbbell Row', 'back', 'dumbbell', 'strength', false),
('Deadlift', 'back', 'barbell', 'strength', false),
('Overhead Press', 'shoulders', 'barbell', 'strength', false),
('Lateral Raise', 'shoulders', 'dumbbell', 'strength', false),
('Arnold Press', 'shoulders', 'dumbbell', 'strength', false),
('Face Pull', 'shoulders', 'cable', 'strength', false),
('Front Raise', 'shoulders', 'dumbbell', 'strength', false),
('Squat', 'legs', 'barbell', 'strength', false),
('Romanian Deadlift', 'legs', 'barbell', 'strength', false),
('Leg Press', 'legs', 'machine', 'strength', false),
('Hip Thrust', 'glutes', 'barbell', 'strength', false),
('Leg Curl', 'legs', 'machine', 'strength', false),
('Leg Extension', 'legs', 'machine', 'strength', false),
('Bulgarian Split Squat', 'legs', 'dumbbell', 'strength', false),
('Calf Raise', 'legs', 'machine', 'strength', false),
('Barbell Curl', 'biceps', 'barbell', 'strength', false),
('Hammer Curl', 'biceps', 'dumbbell', 'strength', false),
('Incline Dumbbell Curl', 'biceps', 'dumbbell', 'strength', false),
('Tricep Pushdown', 'triceps', 'cable', 'strength', false),
('Skull Crusher', 'triceps', 'barbell', 'strength', false),
('Overhead Tricep Extension', 'triceps', 'dumbbell', 'strength', false),
('Plank', 'core', 'bodyweight', 'bodyweight', false),
('Sit-up', 'core', 'bodyweight', 'bodyweight', false),
('Ab Wheel Rollout', 'core', 'none', 'bodyweight', false),
('Running', 'cardio', 'none', 'run', false),
('Rowing Machine', 'cardio', 'machine', 'cardio', false)
ON CONFLICT DO NOTHING;
