/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#2a2a2a',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'outline': '#99907c',
        'on-secondary-container': '#9bb3fd',
        'surface-variant': '#353534',
        'secondary-fixed-dim': '#b3c5ff',
        'secondary-fixed': '#dbe1ff',
        'surface-bright': '#3a3939',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'on-error': '#690005',
        'secondary': '#b3c5ff',
        'on-tertiary': '#003732',
        'inverse-on-surface': '#313030',
        'on-surface': '#e5e2e1',
        'primary-container': '#d4af37',
        'on-secondary-fixed-variant': '#2a4386',
        'tertiary': '#46e4d4',
        'surface-dim': '#131313',
        'inverse-primary': '#735c00',
        'on-tertiary-container': '#004e47',
        'on-surface-variant': '#d0c5af',
        'surface-container-highest': '#353534',
        'primary': '#f2ca50',
        'on-tertiary-fixed': '#00201d',
        'tertiary-fixed': '#61f9e9',
        'surface': '#131313',
        'inverse-surface': '#e5e2e1',
        'on-primary-container': '#554300',
        'primary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#3adccc',
        'surface-tint': '#e9c349',
        'background': '#131313',
        'outline-variant': '#4d4635',
        'on-primary': '#3c2f00',
        'tertiary-container': '#09c8b9',
        'error-container': '#93000a',
        'on-background': '#e5e2e1',
        'on-tertiary-fixed-variant': '#005049',
        'on-secondary': '#0d2c6e',
        'primary-fixed-dim': '#e9c349',
        'error': '#ffb4ab',
        'secondary-container': '#2a4386',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-fixed': '#00174a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'gutter': '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-xl': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'serif': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.2em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
